version: 0.1
phases:
  install:
    commands:
      - pip install pytest
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ip-list-parser-code-bucket --output-template-file outputSamTemplate.yaml
      - python -m pytest tests

artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml